# Generated by Django 5.0.6 on 2024-05-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pokemon_id', models.IntegerField(unique=True)),
                ('types', models.JSONField()),
                ('abilities', models.JSONField()),
                ('base_stats', models.JSONField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('sprite_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
