# Generated by Django 5.0.6 on 2024-05-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokeApp', '0003_remove_pokemon_pokemon_id_pokemon_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_id',
            field=models.CharField(default='123', max_length=255),
            preserve_default=False,
        ),
    ]
